/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CustomerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public CustomerDashboard() {
        initComponents();
        ImageIcon img = new ImageIcon("src/media/shoppingbag.png");
       this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClothes = new javax.swing.JButton();
        lblWelcomeAdminPanel = new javax.swing.JLabel();
        btnKitchenware = new javax.swing.JButton();
        btnShoes = new javax.swing.JButton();
        btnAvailableProd = new javax.swing.JButton();
        btnSports = new javax.swing.JButton();
        btnToys = new javax.swing.JButton();
        btnOrderList = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        lblSignout = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Dashboard");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,70));

        btnClothes.setBackground(new java.awt.Color(195, 17, 17));
        btnClothes.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnClothes.setForeground(new java.awt.Color(255, 255, 255));
        btnClothes.setText("cLOTHES");
        btnClothes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClothes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClothesMouseClicked(evt);
            }
        });

        lblWelcomeAdminPanel.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        lblWelcomeAdminPanel.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcomeAdminPanel.setText("                                                    dASHBOARD");

        btnKitchenware.setBackground(new java.awt.Color(195, 17, 17));
        btnKitchenware.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnKitchenware.setForeground(new java.awt.Color(255, 255, 255));
        btnKitchenware.setText("kITCHENwARES");
        btnKitchenware.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKitchenware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitchenwareActionPerformed(evt);
            }
        });

        btnShoes.setBackground(new java.awt.Color(195, 17, 17));
        btnShoes.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnShoes.setForeground(new java.awt.Color(255, 255, 255));
        btnShoes.setText("sHOES");
        btnShoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShoesMouseClicked(evt);
            }
        });
        btnShoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShoesActionPerformed(evt);
            }
        });

        btnAvailableProd.setBackground(new java.awt.Color(195, 17, 17));
        btnAvailableProd.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnAvailableProd.setForeground(new java.awt.Color(255, 255, 255));
        btnAvailableProd.setText("aVAILABLE PRODUCTS");
        btnAvailableProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAvailableProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAvailableProdMouseClicked(evt);
            }
        });

        btnSports.setBackground(new java.awt.Color(195, 17, 17));
        btnSports.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnSports.setForeground(new java.awt.Color(255, 255, 255));
        btnSports.setText("sPORTS");
        btnSports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSportsActionPerformed(evt);
            }
        });

        btnToys.setBackground(new java.awt.Color(195, 17, 17));
        btnToys.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnToys.setForeground(new java.awt.Color(255, 255, 255));
        btnToys.setText("tOYS");
        btnToys.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnToys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToysActionPerformed(evt);
            }
        });

        btnOrderList.setBackground(new java.awt.Color(195, 17, 17));
        btnOrderList.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnOrderList.setForeground(new java.awt.Color(255, 255, 255));
        btnOrderList.setText("Order Lists");
        btnOrderList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrderList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderListActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(195, 17, 17));
        btnLogout.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Log Out");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblWelcomeAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnClothes, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKitchenware, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAvailableProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOrderList)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnShoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSports)
                        .addGap(18, 18, 18)
                        .addComponent(btnToys))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnLogout)))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblWelcomeAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClothes, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKitchenware, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShoes, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSports, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToys, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvailableProd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrderList, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(317, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 890, 610));

        jPanel2.setBackground(new java.awt.Color(204, 22, 22));

        lblDashboard.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(153, 153, 153));
        lblDashboard.setText("Dashboard");
        lblDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblSignout.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        lblSignout.setForeground(new java.awt.Color(255, 255, 255));
        lblSignout.setText("Sign out");
        lblSignout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSignout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignoutMouseClicked(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("Exit");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSignout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lblSignout, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(334, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 610));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/bacground image.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKitchenwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitchenwareActionPerformed
        try {
            // TODO add your handling code here:
            Kitchenwares kc = new Kitchenwares();
            kc.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(CustomerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnKitchenwareActionPerformed

    private void btnShoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShoesActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginType lt = new LoginType();
        int res;
        res = JOptionPane.showConfirmDialog(this, "Are you sure to Logout?" );
        switch (res) {
            case 0:
                
                lt.setVisible(true);    //opens the LoginType Jframe.
                this.setVisible(false);     //closes the current JFrame form.
                break;
        //this.setVisible(true);
            default:
                break;
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAvailableProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAvailableProdMouseClicked
        // TODO add your handling code here:
        AvailableProducts ap;
        try {
            ap = new AvailableProducts();
            ap.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(CustomerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAvailableProdMouseClicked

    private void lblSignoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignoutMouseClicked
        // TODO add your handling code here:
        LoginType lt = new LoginType();
        int res;
        res = JOptionPane.showConfirmDialog(this, "Are you sure to Logout?" );
        switch (res) {
            case 0:
                
                lt.setVisible(true);    //opens the LoginType Jframe.
                this.setVisible(false);     //closes the current JFrame form.
                break;
        //this.setVisible(true);
            default:
                break;
        }
    }//GEN-LAST:event_lblSignoutMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        int res;
        res = JOptionPane.showConfirmDialog(this, "Are You sure to exit?");
        System.out.println(res);
        if (res == 0){  //If the user selects Yes then the Window closes.
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
    }//GEN-LAST:event_lblExitMouseClicked

    private void btnClothesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClothesMouseClicked
        // TODO add your handling code here:
        Clothes c;
        try {
            c = new Clothes();
            c.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(CustomerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnClothesMouseClicked

    private void btnShoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShoesMouseClicked
        try {
            // TODO add your handling code here:
            ShoesList sl = new ShoesList();
            sl.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(CustomerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnShoesMouseClicked

    private void btnOrderListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderListActionPerformed
        try {
            // TODO add your handling code here:
            OrderListCustomer olc = new OrderListCustomer();
            olc.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(CustomerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOrderListActionPerformed

    private void btnSportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSportsActionPerformed
        try {
            // TODO add your handling code here:
            Sports sp = new Sports();
            sp.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(CustomerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSportsActionPerformed

    private void btnToysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToysActionPerformed
        // TODO add your handling code here:
        Toys t;
        try {
            t = new Toys();
            t.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(CustomerDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnToysActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CustomerDashboard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvailableProd;
    private javax.swing.JButton btnClothes;
    private javax.swing.JButton btnKitchenware;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOrderList;
    private javax.swing.JButton btnShoes;
    private javax.swing.JButton btnSports;
    private javax.swing.JButton btnToys;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblSignout;
    private javax.swing.JLabel lblWelcomeAdminPanel;
    // End of variables declaration//GEN-END:variables
}
