/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
/**
 *
 * @author User
 */
import javax.swing.ImageIcon;
public class LoginType extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public LoginType() {
        initComponents();
       ImageIcon img = new ImageIcon("src/media/shoppingbag.png");
       this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdminLoginLogo = new javax.swing.JButton();
        btnAdminLogin = new javax.swing.JButton();
        btnCustomerLogin = new javax.swing.JButton();
        btnCustomerLoginImage = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblBgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Type");
        setMaximumSize(new java.awt.Dimension(1070, 611));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdminLoginLogo.setBackground(new java.awt.Color(96, 62, 42));
        btnAdminLoginLogo.setIcon(new javax.swing.ImageIcon("D:\\Third Sem\\Assignments\\Assignment_of_JAVA\\icons\\User.png")); // NOI18N
        btnAdminLoginLogo.setAlignmentY(0.0F);
        btnAdminLoginLogo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.black));
        btnAdminLoginLogo.setBorderPainted(false);
        btnAdminLoginLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminLoginLogo.setIconTextGap(0);
        btnAdminLoginLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminLoginLogoMouseClicked(evt);
            }
        });
        getContentPane().add(btnAdminLoginLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 100, 90));

        btnAdminLogin.setBackground(new java.awt.Color(182, 82, 38));
        btnAdminLogin.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        btnAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminLogin.setText("Admin Login");
        btnAdminLogin.setBorderPainted(false);
        btnAdminLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminLoginMouseClicked(evt);
            }
        });
        getContentPane().add(btnAdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));

        btnCustomerLogin.setBackground(new java.awt.Color(182, 82, 38));
        btnCustomerLogin.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        btnCustomerLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomerLogin.setText("Customer Login");
        btnCustomerLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCustomerLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerLoginMouseClicked(evt);
            }
        });
        getContentPane().add(btnCustomerLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, -1, -1));

        btnCustomerLoginImage.setBackground(new java.awt.Color(96, 62, 42));
        btnCustomerLoginImage.setForeground(new java.awt.Color(51, 51, 51));
        btnCustomerLoginImage.setIcon(new javax.swing.ImageIcon("D:\\Third Sem\\Assignments\\Assignment_of_JAVA\\icons\\User.png")); // NOI18N
        btnCustomerLoginImage.setAlignmentY(0.0F);
        btnCustomerLoginImage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.darkGray));
        btnCustomerLoginImage.setBorderPainted(false);
        btnCustomerLoginImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCustomerLoginImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerLoginImageActionPerformed(evt);
            }
        });
        getContentPane().add(btnCustomerLoginImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 100, 90));

        jLabel2.setBackground(new java.awt.Color(63, 33, 8));
        jLabel2.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select User Type");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, 60));

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,90));

        jLabel1.setBackground(new java.awt.Color(141, 63, 43));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to All in 1 Store");
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1070, 610);

        lblBgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/backiee-10804-landscape.jpg"))); // NOI18N
        lblBgImage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblBgImage.setOpaque(true);
        jPanel1.add(lblBgImage);
        lblBgImage.setBounds(0, 0, 1080, 607);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 1070, 610));

        setSize(new java.awt.Dimension(1085, 647));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerLoginImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerLoginImageActionPerformed
        // TODO add your handling code here:
        CustomerLogin cl = new CustomerLogin();
        cl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCustomerLoginImageActionPerformed

    private void btnAdminLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminLoginMouseClicked
        // TODO add your handling code here:
        AdminLogin al= new AdminLogin();
        al.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdminLoginMouseClicked

    private void btnAdminLoginLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminLoginLogoMouseClicked
        // TODO add your handling code here:
        AdminLogin al= new AdminLogin();
        al.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdminLoginLogoMouseClicked

    private void btnCustomerLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerLoginMouseClicked
        // TODO add your handling code here:
        CustomerLogin cl = new CustomerLogin();
        cl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCustomerLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginType().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JButton btnAdminLoginLogo;
    private javax.swing.JButton btnCustomerLogin;
    private javax.swing.JButton btnCustomerLoginImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBgImage;
    // End of variables declaration//GEN-END:variables

   
}
