/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bll.CustomerLoginBll;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ShoesList extends javax.swing.JFrame {
    public void shoeList() throws FileNotFoundException, IOException{
       String[] columnName = new String[5];
       columnName[0] = "Product ID";
       columnName[1] = "Name";
       columnName[2] = "Rate";
       columnName[3] = "Quantity";
       columnName[4] = "Category";
       
       

        File file = new File("src/textFiles/Product.txt");
        BufferedReader br = new BufferedReader(new FileReader(file));
        tblProductList.setRowHeight(30);
        DefaultTableModel model = (DefaultTableModel) tblProductList.getModel();
        model.setColumnIdentifiers(columnName);
        
       Object[] tableLines = br.lines().toArray();
       int i;
       
       for(i=0; i<tableLines.length;i++){
           String line = tableLines[i].toString().trim();
           String[] tableRow = line.split(",");
           if("Shoes".equals(tableRow[4])){
           model.addRow(tableRow);
           }
       }
       
    }

    /**
     * Creates new form AdminDashboard
     * @throws java.io.FileNotFoundException
     */
    public ShoesList() throws FileNotFoundException, IOException {
        initComponents();
        ImageIcon img = new ImageIcon("src/media/shoppingbag.png");
       this.setIconImage(img.getImage());
       shoeList();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblWelcomeAdminPanel = new javax.swing.JLabel();
        lblProdName = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        txtProdName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        btnCheckout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductList = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        lblSignout = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Panel");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,70));

        lblWelcomeAdminPanel.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        lblWelcomeAdminPanel.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcomeAdminPanel.setText("SHOes Section");

        lblProdName.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        lblProdName.setForeground(new java.awt.Color(255, 255, 255));
        lblProdName.setText("Product Name:");

        lblQuantity.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantity.setText("Quantity:");

        btnCheckout.setBackground(new java.awt.Color(189, 20, 20));
        btnCheckout.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        btnCheckout.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckout.setText("Check Out");
        btnCheckout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseClicked(evt);
            }
        });

        tblProductList.setBackground(new java.awt.Color(2, 0, 0));
        tblProductList.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        tblProductList.setForeground(new java.awt.Color(255, 255, 255));
        tblProductList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblProductList.setFillsViewportHeight(true);
        tblProductList.setFocusable(false);
        tblProductList.setRequestFocusEnabled(false);
        tblProductList.getTableHeader().setReorderingAllowed(false);
        tblProductList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblProductListKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProdName)
                            .addComponent(lblQuantity))
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProdName, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(txtQuantity)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(btnCheckout)))
                .addContainerGap(325, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblWelcomeAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 78, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcomeAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdName)
                    .addComponent(txtProdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQuantity)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnCheckout)
                .addGap(78, 78, 78))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 890, 610));

        jPanel2.setBackground(new java.awt.Color(204, 22, 22));

        lblDashboard.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard.setText("Dashboard");
        lblDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardMouseClicked(evt);
            }
        });

        lblSignout.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        lblSignout.setForeground(new java.awt.Color(255, 255, 255));
        lblSignout.setText("Sign out");
        lblSignout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSignout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignoutMouseClicked(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("Exit");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSignout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(lblSignout, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 610));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/bacground image.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseClicked
        // TODO add your handling code here:
        CustomerDashboard ad = new CustomerDashboard();
        ad.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblDashboardMouseClicked
    public void purchaseShoes() throws IOException{
        File file = new File("src/textFiles/Product.txt");
        File f = new File("src/textFiles/Order.txt");
        CustomerLoginBll clb = new CustomerLoginBll();
        BufferedReader br;
        String prodname = txtProdName.getText();
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
            LocalDateTime now = LocalDateTime.now();  
              
        try {
            br = new BufferedReader(new FileReader(file));
            if(!f.exists()){
                f.createNewFile();
                
            }
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(f,true)); PrintWriter pw = new PrintWriter(bw)) {
                BufferedReader brUser = new BufferedReader(new FileReader("src/textFiles/activeUser.txt"));
                Object[] tableData = brUser.lines().toArray();
                String lineUser = tableData[0].toString().trim();
                String[] rowData = lineUser.split(",");
                Object[] tableLines = br.lines().toArray();
                int i = 0;
                
                while(i < tableLines.length){
                    // System.out.println("Inside While");
                    String line = tableLines[i].toString().trim();      //stores the lines as a string in a array tableLines.
                    String[] tableRow = line.split(",");
                    float rate = Float.parseFloat(tableRow[2]);
                    if(prodname.equals(tableRow[1]) ){
                        try{
                            int quantity = Integer.parseInt(txtQuantity.getText()); 
                            pw.println(rowData[0]+","+ rowData[1]+ ","+ prodname + "," +"Shoes,"+ quantity +","+ rate*quantity+","+ dtf.format(now) );
                        }
                        catch(NumberFormatException e){
                            JOptionPane.showMessageDialog(this,"Please enter numeric data");
                        }
                    } 
                    
                    i++;
                    
           
                    
                }
                pw.flush();
                pw.close();
            
            
                try (BufferedWriter bwp = new BufferedWriter(new FileWriter(file)); PrintWriter pwp = new PrintWriter(bwp)) {
                    System.out.println("Out of first loop");
                    for(i=0; i<tableLines.length;i++){
                        String lines = tableLines[i].toString().trim();
                        String[] tableRows = lines.split(",");
                        //System.out.println(i);
                        
                        
                        int quantity = Integer.parseInt(txtQuantity.getText());
                        int stockQuantity = Integer.parseInt(tableRows[3]);
                        if(prodname.equals(tableRows[1]) ){
                            int newStock = stockQuantity-quantity;
                            if(newStock > 0){
                            pwp.println(tableRows[0]+","+tableRows[1]+","+tableRows[2]+","+newStock+","+tableRows[4]);
                            // pw.println(clb.getCustomerId()+","+ clb.getUsername() + ","+ prodname + "," +"Clothes,"+ quantity +","+ rate*quantity+","+ dtf.format(now)
                            }
                        }
                        else{
                            pwp.println(lines);
                        }
                    }
                    pwp.flush();
                    pwp.close();
                }
                    
                    
             
    }}   catch (FileNotFoundException ex) {
            Logger.getLogger(ShoesList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ShoesList.class.getName()).log(Level.SEVERE, null, ex);
        }}
    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        int res;
        res = JOptionPane.showConfirmDialog(this, "Are You sure to exit?");
        System.out.println(res);
        if (res == 0){
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
       
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblSignoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignoutMouseClicked
        LoginType lt = new LoginType();
        int res;
        res = JOptionPane.showConfirmDialog(this, "Are you sure to Logout?" );
        switch (res) {
            case 0:
                
                lt.setVisible(true);    //opens the LoginType Jframe.
                this.setVisible(false);     //closes the current JFrame form.
                break;
        //this.setVisible(true);
            default:
                break;
        }
// TODO add your handling code here:
    }//GEN-LAST:event_lblSignoutMouseClicked

    private void btnCheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseClicked
        
        if(!"".equals(txtProdName.getText())  && !"".equals(txtQuantity.getText())){
            try {
            // TODO add your handling code here:
                purchaseShoes();
                tblProductList.setModel(new DefaultTableModel(null, new String[]{"ID","Name","Rate","Quantity","Category"}));
                shoeList();
                JOptionPane.showMessageDialog(this, "Product Purcased successfully.");
                txtProdName.setText(null);
                txtQuantity.setText(null);
            } 
            catch (IOException ex) {
                Logger.getLogger(ShoesList.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        else{
            JOptionPane.showMessageDialog(this, "Please fill all the fields.");
        }
    }//GEN-LAST:event_btnCheckoutMouseClicked

    private void tblProductListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblProductListKeyPressed
        // TODO add your handling code here:
        boolean edit = tblProductList.isEditing();
        
        if(edit == true){
            JOptionPane.showMessageDialog(this,"You cannot edit this table.");
        }
    }//GEN-LAST:event_tblProductListKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShoesList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShoesList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShoesList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShoesList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new ShoesList().setVisible(true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ShoesList.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ShoesList.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblProdName;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblSignout;
    private javax.swing.JLabel lblWelcomeAdminPanel;
    private javax.swing.JTable tblProductList;
    private javax.swing.JTextField txtProdName;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
